config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

	# Sidekiq Worker Manager
	authenticate :admin do
		mount Sidekiq::Web, at: '/admin/sidekiq-manager'
	end

	root 'home#index'
	resources :order_items
	resource :shopping_carts
	get '/service-worker.js' => "service_worker#service_worker"
	get '/manifest.json' => "service_worker#manifest"
	get '/offline.html' => "service_worker#offline"

	devise_for :admins, controllers: {
		sessions: 'admins/sessions'
	}

	resources :categorias
	resources :checkout, except: [:destroy]
	resources :payments, only: [:new, :create, :destroy] do
		collection { post 'compra_click' }
	end
	patch '/extend_timer' => 'payments#extend_timer'
	get '/gracias/:id' => 'payments#gracias', as: "gracias"

	namespace :admin do
		get '/' => 'home#index'
		resources :products
		resources :soldout_products, only: [:index]
		resources :orders
		resources :bulk_tasks
		namespace :orders do
			get 'shipped/index'
			get 'declined/index'
		end
	end

	get 'test/index'
end

app/models/order.rb
class Order < ApplicationRecord
	extend FriendlyId
	friendly_id :slug_it, use: :slugged

	has_many :order_items, dependent: :destroy
	has_many :products, through: :order_items

	has_one :address, as: :source, dependent: :destroy
	has_one :payment, dependent: :destroy

	before_save :set_subtotal
	before_save :set_shipping

	def subtotal
		order_items.collect { |order_item| order_item.valid? ? (order_item.unit_price * order_item.quantity) : 0 }.sum
	end

	def subtotal_net
		order_items.collect { |order_item| (order_item.unit_price * order_item.quantity) }.sum
	end

	def shipping
		address&.municipio == "distrito_central" ? 80 : 0
	end

	def remove_associations
		# we are doing this when purchase time has expired or denied
		self&.address&.destroy
		return_products
		self.order_items.map(&:destroy)
	end

	def reserve_products
		self.order_items.each do |order_item|
			availability = order_item.product.quantity - order_item.quantity
			allowed_order_quantity = availability < 0 ? order_item.product.quantity : order_item.quantity
			order_item.product.update_attributes(quantity: order_item.product.quantity - allowed_order_quantity)
			order_item.update_attributes(quantity: allowed_order_quantity)
		end
	end

	def return_products
		self.order_items.each do |order_item|
			order_item.product.update_attributes(quantity: order_item.product.quantity + order_item.quantity)
		end
	end

	private

	def set_subtotal
		self[:subtotal] = subtotal
	end

	def set_shipping
		self[:shipping] = shipping
	end

	def slug_it
		slugs = []
		3.times do
			slugs << "orden" + "-" + SecureRandom.urlsafe_base64(7).parameterize.downcase
		end
		slugs
	end
end

app/controllers/admin/orders/declined_controller.rb
class Admin::Orders::DeclinedController < ApplicationController
	layout "admin"

	def index
		@orders = Order.where(declined: true).order("updated_at DESC")
	end
end

app/controllers/admin/orders/shipped_controller.rb
class Admin::Orders::ShippedController < ApplicationController
	layout "admin"

	def index
		@orders = Order.where(shipped: true).order("updated_at DESC")
	end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def index
    @orders ||= Order.where(submitted: true, shipped: false, declined: false).order("updated_at DESC")
  end

  def show
    @browser = Browser.new("Some User Agent", accept_language: "en-us")
  end

  def edit
  end

  def update
    respond_to do |format|
      if @order.update(shipped: true)
        format.html { redirect_to admin_orders_path, notice: 'Preparar orden para envío' }
      else
        flash[:alert] = "Por favor tratar de nuevo, #{@order.errors.full_messages.to_sentence}"
        redirect_back(fallback_location: admin_orders_path)
      end
    end
  end

  def destroy
    @order.update(admin_order_params)
    @order.return_products
    respond_to do |format|
      format.html { redirect_to admin_orders_path, error: 'Orden cancelada' }
    end
  end

  private

  def set_order
    @order = Order.friendly.find(params[:id])
  end

  def admin_order_params
    params.require(:order).permit(:reason_for_decline, :declined)
  end
end

app/helpers/admin/orders/declined_helper.rb
module Admin::Orders::DeclinedHelper
end

app/helpers/admin/orders/shipped_helper.rb
module Admin::Orders::ShippedHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/orders/_navigation_tabs.html.erb
<ul class="nav nav-tabs nav-fill pt-2 mb-5 mt-3">
	<li class="nav-link <%= 'active' if active == 'orders' %>">
		<%= link_to admin_orders_path,
			class: "text-decoration-none text-dark font-weight-bold" do %>
			<span>Ordenes Nuevas</span>
		<% end %>
	</li>
	<li class="nav-link <%= 'active' if active == 'orders_all' %>">
		<%= link_to admin_orders_path,
			class: "text-decoration-none text-dark font-weight-bold" do %>
			<span>Todas las Ordenes</span>
		<% end %>
	</li>
	<li class="nav-link <%= 'active' if active == 'orders_declined' %>">
		<%= link_to admin_orders_path,
			class: "text-decoration-none text-dark font-weight-bold" do %>
			<span>Ordenes Declinadas</span>
		<% end %>
	</li>

</ul>

app/views/admin/orders/edit.html.erb
<h1>Editing Admin Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<%= render 'admin/shared/order_navigation', active: "orders" %>

<div id="orders" class="container-fluid">
  <div class="table-responsive">
    <h4 class="mb-4">Ordenes Nuevas</h4>
    <div class="shadow-sm">
      <% unless @orders.empty? %>
        <table id="orders-table"
          class="table table-centered table-nowrap rounded table-hover align-middle"
          data-toggle="table"
          data-search="true">
          <!-- <div class="btn-group float-right mt-3 mb-4">
            <%#= link_to "#",
              class: "btn btn-sm btn-outline-success" do %>
              <i class="far fa-file-excel"></i>
              Exportar
            <%# end %>
          </div> -->
            <thead class="thead-light">
                <tr>
                    <th data-sortable="true" class="border-0">#</th>
                    <th data-sortable="true" class="border-0">Id</th>
                    <th data-sortable="true" class="border-0">Items</th>
                    <th data-sortable="true" class="border-0">Correo</th>
                    <th data-sortable="true" class="border-0">
                      Fecha de Compra
                    </th>
                    <th data-sortable="true" class="border-0">Total</th>
                    <th class="border-0">Enviar</th>
                    <th class="border-0">Más</th>
                </tr>
            </thead>

            <tbody>
              <% @orders.each_with_index do |order, i| %>
                <tr id="new-order-<%= order.slug %>">
                  <td class="border-0 text-black-50">
                    <%= i + 1 %>
                  </td>
                  <td class="border-0 font-weight-bold"
                    style="min-width: 12rem;">
                    <%= link_to order.slug, admin_order_path(order),
                      class: "text-decoration-none text-black-50" %>
                  </td>

                  <td class="border-0">
                    <%=  order.order_items.pluck(:quantity).reduce(:+) %>
                  </td>

                  <td class="border-0">
                    <%=  order&.address&.correo %>
                  </td>

                  <td class="border-0" style="min-width: 14rem;">
                    <%=  order.payment.updated_at
                      .strftime("%e de %b %y @ %l:%M %p") %>
                  </td>

                  <td class="border-0"
                    style="min-width: 8rem;">
                    <%= number_to_currency(order.subtotal_net,
                      unit: "Lps. ", separator: ".", delimiter: ",") %>
                  </td>

                  <td class="border-0">
                    <div class="form-check form-check-inline">
                      <input id="<%= order.slug %>"
                        class="form-check-input"
                        type="checkbox"
                        data-controller="order"
                        data-action="click->order#ship"
                        data-reflex="Order#ship">
                    </div>
                  </td>

                  <td class="border-0">
                    <div class="btn-group">
                      <button class="btn btn-link text-dark m-0 p-0"
                        data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                          <i class="fas fa-ellipsis-h fa-lg text-muted"></i>
                          <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <div class="dropdown-menu">
                        <%= link_to admin_order_path(order),
                          class: "dropdown-item" do %>
                          <span class="fas fa-eye mr-2"></span>
                          Ver Detalle
                        <% end %>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
        </table>
      <% else %>
        <h4 class="text-muted text-center py-4 my-4">
          No hay ordenes, ponete las pilas!
        </h4>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<h1>New Admin Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<%= render 'admin/shared/order_navigation', active: "orders" %>

<div id="order" class="container-fluid">
	<div class="row">
		<div class="col-12 col-md-8">
			<h5>
				<%= @order.payment.updated_at
					.strftime("%e de %b %y @ %l:%M %p") %>
			</h5>
		</div>
		<div class="col-12 col-md-4">
			<%= link_to admin_orders_path,
				class: "btn btn-outline-dark btn-sm float-right mr-1" do %>
				<i class="fas fa-chevron-left"></i>
				Regresar
			<% end %>
		</div>
	</div>
	<hr class="my-4">
	<div class="row">
		<div class="col-12 col-md-7">
			<div class="text-center">
				<% if @order.payment.payment_method == "compra_click" %>
					<p class="text-center">
						Order solicitada con compra click
					</p>

					<% if device == "mobile" %>
					  	<a href="https://wa.me/+504<%= @order.address.telefono.tr(" \t\r\n", '').gsub(/[-!?¿¡.\/,&()]/, '') %>" target="_blank">
					  		<%= @order.address.telefono %>
					  	</a>
					<% else %>
						<a href="https://web.whatsapp.com/send?phone=+504<%= @order.address.telefono.tr(" \t\r\n", '').gsub(/[-!?¿¡.\/,&()]/, '') %>" target="_blank">
							<%= @order.address.telefono %>
						</a>
					<% end %>
				<% else %>
					<figure class="figure">
					<%= image_tag @order.payment.file,
						class: "figure-img img-fluid rounded",
						alt: "foto de deposito" %>
						<figcaption class="figure-caption">
							<%= link_to 'Descargar comprobante',
								rails_blob_path(@order.payment.file,
								disposition: "attachment"),
								class: "text-decoration-none text-muted" %>
						</figcaption>
					</figure>
				<% end %>
			</div>
		</div>
		<div class="col-12 col-md-5">
			<ul class="list-group list-group-flush">
			  <li class="list-group-item font-weight-bold">
			  	<i class="text-muted mr-2 fas fa-user"></i>
			  	<%= @order&.address&.username %>
			  </li>
			  <li class="list-group-item">
			  	<i class="text-muted mr-2 fas fa-at"></i>
			  	<%= @order&.address&.correo %>
			  </li>
			  <li class="list-group-item">
			  	<i class="text-muted mr-2 fas fa-phone"></i>
			  	<%= @order&.address&.telefono %>
			  	<% unless @order.address.telefono_alternativo.empty? %>
			  		<%= " / #{@order.address.telefono_alternativo}" %>
			  	<% end %>
			  </li>
			  <li class="list-group-item">
			  	<i class="text-muted mr-2 fas fa-map-marked-alt"></i>
			  	<%= @order&.address&.one_line_format %>
			  </li>
			  <li class="list-group-item">
			  	<i class="text-muted mr-2 fas fa-location-arrow"></i>
			  	<%= @order&.address&.referencia %>
			  </li>
			  <li class="list-group-item">
			  	<i class="text-muted mr-2 fas fa-book-open"></i>
			  	<%= @order&.address&.notas %>
			  </li>
			</ul>
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-12 my-3">
			<table
				class="table table-hover align-middle">
			  	<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Foto</th>
						<th scope="col">Nombre</th>
						<th scope="col">Cantidad</th>
						<th scope="col">P/U</th>
						<th scope="col">SubTotal</th>
					</tr>
			  	</thead>
				<tbody>
					<% @order.order_items.each_with_index do |item, i| %>
						<tr>
							<th scope="row"><%= i + 1 %></th>
							<td>
								<% if item.product.main_image.attached? %>
									<%= image_tag item.product.main_image,
										class: "img-thumbnail", style: 'height:4vw;width:auto' %>
								<% else %>
									<%= image_tag 'otra_vez_blanco.jpg',
										class: "img-thumbnail", style: 'height:4vw;width:auto' %>
								<% end %>
							</td>
							<td><%= item.product.title %></td>
							<td><%= item.quantity %></td>
							<td style="min-width: 8rem;">
								<%= number_to_currency(item.unit_price,
							  		unit: "Lps. ", separator: ".",
							  		delimiter: ",") %>
							</td>
							<td style="min-width: 8rem;">
								<%= number_to_currency(item.total_price,
							  		unit: "Lps. ", separator: ".",
							  		delimiter: ",") %>
						 	</td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<div class="container mb-1">
				<div class="row">
					<div class="col-12 d-flex justify-content-end">
						<h5 class="align-middle mr-5">Total</h5>
						<h5 class="font-weight-bolder align-middle mx-5">
							<%= number_to_currency(@order.subtotal_net,
								unit: "Lps. ", separator: ".",
								delimiter: ",") %>
						</h5>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr>
	<div class="row mb-5">
		<div class="col-12 col-md-6">
			<button type="button" class="btn btn-block btn-danger my-3"
				data-toggle="modal" data-target="#orderDecline">
			  Cancelar orden
			</button>
		</div>
		<div class="col-12 col-md-6">
			<%= link_to admin_order_path, method: :patch,
				data: { confirm: 'Confirmar'},
				class: "btn btn-block btn-outline-dark my-3" do %>
				Listo para envío
			<% end %>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="orderDecline" tabindex="-1"
	aria-labelledby="orderDeclineLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="btn-close" data-dismiss="modal"
					aria-label="Close"></button>
			</div>
			<%= form_with(model: [:admin, @order], local: true,
				url: admin_order_path, method: "delete") do |form| %>
				<div class="modal-body">
					<div class="col-12">
						<div class="mb-4">
							<%= form.hidden_field(:declined, value: true ) %>
							<%= label_tag(:reason_for_decline, "Dar una razón") %>
							<%= form.text_field :reason_for_decline, class: "mt-2 form-control", required: true %>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline-secondary"
						data-dismiss="modal">
						Regresar
					</button>
					<button type="submit" class="btn btn-dark">
						Declinar
					</button>
				</div>
			<% end %>
		</div>
	</div>
</div>