config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

	# Sidekiq Worker Manager
	authenticate :admin do
		mount Sidekiq::Web, at: '/admin/sidekiq-manager'
	end

	root 'home#index'
	resources :order_items
	resource :shopping_carts
	get '/service-worker.js' => "service_worker#service_worker"
	get '/manifest.json' => "service_worker#manifest"
	get '/offline.html' => "service_worker#offline"

	devise_for :admins, controllers: {
		sessions: 'admins/sessions'
	}

	resources :categorias
	resources :checkout, except: [:destroy]
	resources :payments, only: [:new, :create, :destroy] do
		collection { post 'compra_click' }
	end
	patch '/extend_timer' => 'payments#extend_timer'
	get '/gracias/:id' => 'payments#gracias', as: "gracias"

	namespace :admin do
		get '/' => 'home#index'
		resources :products
		resources :soldout_products, only: [:index]
		resources :orders
		resources :bulk_tasks
		namespace :orders do
			get 'shipped/index'
			get 'declined/index'
		end
	end

	get 'test/index'
end

app/views/shared/_added_to_cart_modal.html.erb
<div class="modal fade" id="addedToCart" tabindex="-1"
	aria-labelledby="addedToCartLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-body text-center">
				<h5 class="modal-title py-3"
					id="addedToCartLabel">
					Producto Agregado
					<i class="text-success fas fa-check ml-2"></i>
				</h5>
			</div>

			<div class="footer">
				<div class="container">
					<div class="row">
						<div class="col-12 col-md-6">
							<button type="button"class="btn btn-outline-secondary btn-block my-3"
								data-dismiss="modal">
								Continuar Comprando
							</button>
						</div>
						<div class="col-12 col-md-6">
							<%= link_to shopping_carts_path,
								id: "shopping_cart",
								class: "btn btn-dark btn-block my-3" do %>
								Ver Carrito
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_admin_nav_bar.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="/admin">
        OtraVez
    </a>
    <button class="navbar-toggler position-absolute d-md-none collapsed"
        type="button" data-toggle="collapse" data-target="#sidebarMenu"
        aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <input class="form-control form-control-dark w-100" type="text"
    placeholder="Nose que buscar aca... talvez quito este search" aria-label="Search">

    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <%= link_to "Me Voy", destroy_admin_session_path,
                method: :delete, class: "nav-link" %>
        </li>
    </ul>
</nav>

app/views/shared/_admin_side_bar.html.erb
<nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
	id="sidebarMenu" >
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link <%= active_class('/admin') %>" aria-current="page" href="/admin">
          <i class="mr-3 fas fa-home"></i>
          Home
        </a>
        <hr>
      </li>
      <li class="nav-item">
        <%= link_to admin_orders_path,
					class: "nav-link #{active_class('/admin/orders')}" do %>
          <i class="mr-3 fas fa-tshirt"></i>
          Ordenes
        <% end %>
        <hr>
      </li>
      <li class="nav-item">
        <%= link_to admin_products_path,
					class: "nav-link #{active_class('/admin/products')}" do %>
          <i class="mr-3 fas fa-tshirt"></i>
          Productos
        <% end %>
        <hr>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" >
          <i class="mr-3 fas fa-user-astronaut"></i>
          Clientes
        </a>
        <hr>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="mr-3 fas fa-pizza-slice"></i>
          Reportes
        </a>
        <hr>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="mr-3 fas fa-store-alt"></i>
          Tienda
        </a>
        <hr>
      </li>
      <li class="nav-item">
        <%= link_to admin_bulk_tasks_path,
					class: "nav-link #{active_class('/admin/bulk_tasks')}" do %>
          <i class="mr-3 fas fa-tshirt"></i>
          Actualizaciones Masivas
        <% end %>
        <hr>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_cart.html.erb
<div class="icon-wrapper mr-2 ml-0 ml-md-5">
	<div class="d-none d-lg-inline-block">
		<svg xmlns="http://www.w3.org/2000/svg" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
		viewBox="0 0 24 24" width="36" height="36"><path class="heroicon-ui" d="M17 16a3 3 0 1 1-2.83 2H9.83a3 3 0 1 1-5.62-.1A3 3 0 0 1 5 12V4H3a1 1 0 1 1 0-2h3a1 1 0 0 1 1 1v1h14a1 1 0 0 1 .9 1.45l-4 8a1 1 0 0 1-.9.55H5a1 1 0 0 0 0 2h12zM7 12h9.38l3-6H7v6zm0 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
	</div>
	<div class="d-lg-none d-inline-block">
		<svg xmlns="http://www.w3.org/2000/svg" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
		viewBox="0 0 24 24" width="28" height="28"><path class="heroicon-ui" d="M17 16a3 3 0 1 1-2.83 2H9.83a3 3 0 1 1-5.62-.1A3 3 0 0 1 5 12V4H3a1 1 0 1 1 0-2h3a1 1 0 0 1 1 1v1h14a1 1 0 0 1 .9 1.45l-4 8a1 1 0 0 1-.9.55H5a1 1 0 0 0 0 2h12zM7 12h9.38l3-6H7v6zm0 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2zm10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
	</div>

	<% if current_order.order_items.size > 0 %>
		<span class="badge">
			<%= current_order.order_items.pluck(:quantity).reduce(:+) %>
		</span>
	<% end %>
</div>

app/views/shared/_cart_subtotal.html.erb
<div class="row justify-content-end py-3">
	<div class="col-12 col-md-6 d-flex justify-content-around justify-content-md-between">
		<h4 class="align-middle">SUBTOTAL</h4>
		<h4 class="font-weight-bolder align-middle">
			<%= number_to_currency(current_order.subtotal,
				unit: "Lps. ", separator: ".", delimiter: ",") %>
		</h4>
	</div>
</div>
<div class="row">
	<div class="col-12 col-md-6">
		<%= link_to root_path,
			class: "btn btn-block btn-outline-dark my-3" do %>
			Continuar Comprando
		<% end %>
	</div>
	<div class="col-12 col-md-6">
		<%= link_to new_checkout_path,
			class: "btn btn-block btn-dark my-3 #{'disabled' if current_order.order_items.empty? }" do %>
			Check Out
		<% end %>
	</div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="container py-4">
    <div class="row">
      <div class="col-12 col-md-6 text-center text-md-left">
        <h3 class="py-3 text-dark">OTRA VEZ</h3>
        <p class="text-muted">
          <i class="fas fa-recycle fa-lg text-success mr-2"></i>
          moda sostenible
        </p>
        <h3 class="py-3 text-dark">MÁS INFORMACIÓN</h3>
        <p class="text-muted">No aceptamos devoluciones</p>
        <p class="text-muted">Para pre-ordenar contactarnos:</p>
        <p class="text-muted">
          <i class="far fa-envelope fa-lg mr-2"></i>
          <a href="mailto:otravez.hn@gmail.com?
						&subject=Hola%20Otra%20Vez"
						class="text-white text-decoration-none">
            otravez.hn@gmail.com
          </a>
        </p>
        <p class="text-muted">
          <i class="fab fa-whatsapp fa-lg mr-2"></i>
          <a href="https://wa.me/98722191"
						class="text-white text-decoration-none">
            8771-0492
          </a>
        </p>
      </div>
      <div class="col-12 col-md-6 text-center text-md-left">
        <h3 class="py-3 text-dark">REDES SOCIALES</h3>
        <div class="d-flex justify-content-around justify-content-md-start">
          <a class="text-muted"
						href="https://www.instagram.com/o.t.r.a.v.e.z/"
						target="_blank">
            <i class="mr-md-5 fab fa-instagram fa-lg"></i>
          </a>
          <a class="text-muted"
						href="mailto:otravez.hn@gmail.com">
            <i class="far fa-envelope fa-lg"></i>
          </a>
        </div>
        <h3 class="py-4 text-dark">MÉTODOS DE PAGO</h3>
        <div class="d-flex justify-content-around justify-content-md-start text-muted">
          <i class="mr-md-5 fas fa-money-bill fa-lg"></i>
          <i class="mr-md-5 fab fa-paypal fa-lg"></i>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg py-3 navbar-light justify-content-center">
  <div class="container-fluid">
    <span class="w-100 d-lg-none d-block"></span>
    <button class="navbar-toggler p-0 border-0" type="button"
      data-toggle="offcanvas">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand mr-0 d-none d-lg-inline-block" href="/">
      <%= image_tag(asset_path('logo.png'), height: 'auto', width: '160') %>
    </a>
    <a class="navbar-brand-two mx-auto d-lg-none d-inline-block" href="/">
      <%= image_tag(asset_path('logo.png'), height: 'auto', width: '120') %>
    </a>
    <div class="navbar-collapse offcanvas-collapse"
      id="navbarsExampleDefault"
      style="margin-left: 0rem;z-index: 999;">
      <ul class="navbar-nav mx-auto my-3 mb-lg-0 h4">
        <li class="my-2 nav-item active">
          <%= link_to "HOMBRE",categorias_path(cat: "hombre"),
            class: "nav-link" %>
        </li>
        <li class="my-2 nav-item">
          <%= link_to "MUJER",categorias_path(cat: "mujer"),
            class: "nav-link" %>
        </li>
        <li class="my-2 nav-item">
          <%= link_to "YOUTH",categorias_path(cat: "youth"),
            class: "nav-link" %>
        </li>
        <!-- <li class="my-2 nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="masMenu"
            data-toggle="dropdown" aria-expanded="false">OTROS</a>
          <ul class="dropdown-menu" aria-labelledby="masMenu">
            <li>
              <%#= link_to "OTROS",categorias_path(cat: "otro"), class: "dropdown-item" %>
            <li>
            <li><a class="dropdown-item" href="#">PAILAS</a></li>
            <li><a class="dropdown-item" href="#">ALGO MAS</a></li>
          </ul>
        </li> -->

        <li class="my-2 nav-item">
          <%= link_to "OTROS",categorias_path(cat: "otro"),
            class: "nav-link" %>
        </li>
      </ul>
    </div>
    <%= link_to shopping_carts_path, id: "shopping_cart" do %>
      <%= render "shared/cart" %>
    <% end %>
  </div>
</nav>

<script type="text/javascript">
  document.querySelector('[data-toggle="offcanvas"]')
  .addEventListener('click', function () {
    document.querySelector('.offcanvas-collapse')
    .classList.toggle('open')
  })
</script>

app/views/shared/_scroll_navbar.html.erb
<div class="nav-scroller bg-white shadow-sm">
  <nav class="nav nav-underline">
    <a class="nav-link active" aria-current="page" href="#">Dashboard</a>
    <a class="nav-link" href="#">
      Friends
      <span class="badge bg-light text-dark rounded-pill align-text-bottom">27</span>
    </a>
    <a class="nav-link" href="#">Explore</a>
    <a class="nav-link" href="#">Suggestions</a>
    <a class="nav-link" href="#">Link</a>
    <a class="nav-link" href="#">Link</a>
    <a class="nav-link" href="#">Link</a>
    <a class="nav-link" href="#">Link</a>
    <a class="nav-link" href="#">Link</a>
  </nav>
</div>