config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

	# Sidekiq Worker Manager
	authenticate :admin do
		mount Sidekiq::Web, at: '/admin/sidekiq-manager'
	end

	root 'home#index'
	resources :order_items
	resource :shopping_carts
	get '/service-worker.js' => "service_worker#service_worker"
	get '/manifest.json' => "service_worker#manifest"
	get '/offline.html' => "service_worker#offline"

	devise_for :admins, controllers: {
		sessions: 'admins/sessions'
	}

	resources :categorias
	resources :checkout, except: [:destroy]
	resources :payments, only: [:new, :create, :destroy] do
		collection { post 'compra_click' }
	end
	patch '/extend_timer' => 'payments#extend_timer'
	get '/gracias/:id' => 'payments#gracias', as: "gracias"

	namespace :admin do
		get '/' => 'home#index'
		resources :products
		resources :soldout_products, only: [:index]
		resources :orders
		resources :bulk_tasks
		namespace :orders do
			get 'shipped/index'
			get 'declined/index'
		end
	end

	get 'test/index'
end

app/models/product.rb
class Product < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged

	has_many :order_items, dependent: :destroy
	has_one_attached :main_image

	scope :existing, lambda { where("quantity > ?", 0) }
	scope :sold_out, lambda { where("quantity <= ?", 0) }
	scope :hombre, lambda { where("category = ?", "hombre").or(where("category = ?", "unisex")) }
	scope :mujer, lambda { where("category = ?", "mujer").or(where("category = ?", "unisex")) }
	scope :youth, lambda { where("category = ?", "youth").or(where("category = ?", "unisex")) }
	scope :otro, lambda { where("category = ?", "otro") }

	def should_generate_new_friendly_id?
		title_changed? || super
	end

	def self.options
	  return %w(polo manga_larga camiseta gorra camisa shorts sin_mangas pantalon otro)
	end

	def self.sizes
	  return %w(fits_all xxs xs s m l xl 2xl 3xl 4xl 00 0 2 4 6 8 10 12 14 16 26 28 30 32 34 36 38 40)
	end

	def self.fits_like
	  return %w(real xxs xs s m l xl 2xl 3xl 4xl 00 0 2 4 6 8 10 12 14 16 26 28 30 32 34 36 38 40)
	end

	def self.quality
	  return %w(usado nuevo)
	end

	def self.categories
		return %w(hombre mujer youth unisex otro)
	end

	def self.subcategories
		return %w(adulto niño youth otro)
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def index
    @products = Product.existing.all.order("created_at DESC")
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    if !Rails.env.development? && admin_product_params[:main_image].present?
      path = admin_product_params[:main_image].tempfile.path
      ImageProcessing::MiniMagick.source(path)
        .resize_to_limit(900, 900)
        .call(destination: path)
      ImageOptim.new.optimize_image!(path)
    end

    @product = Product.new(admin_product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_path, notice: 'Salvado' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if !Rails.env.development? && admin_product_params[:main_image].present?
      path = admin_product_params[:main_image].tempfile.path
      ImageProcessing::MiniMagick.source(path)
        .resize_to_limit(900, 900)
        .call(destination: path)
      ImageOptim.new.optimize_image!(path)
    end

    respond_to do |format|
      if @product.update(admin_product_params)
        format.html { redirect_to admin_products_path, notice: 'Producto modificado' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(:title, :price, :main_image, :quantity, :category, :option, :size,
        :fit, :brand, :quality, :subcategory)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="container mb-5">
  <%= form_with(model: [:admin, product], local: true) do |f| %>
    <div class="row mb-4">
      <div class="col-12 col-md-6 mb-4">
        <%= label_tag(:title, "Nombre") %>
        <%= f.text_field :title, class: "form-control", required: true %>
      </div>
      <div class="col-12 col-md-6">
        <%= label_tag(:brand, "Marca") %>
        <%= f.text_field :brand, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-6">
        <div class="mb-4">
          <%= label_tag(:price, "Precio") %>
          <%= f.number_field :price, class: "form-control",
            required: true %>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="mb-4">
          <%= label_tag(:quantity, "Cantidad") %>
          <%= f.number_field :quantity, class: "form-control",
            required: true %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-md-4">
        <div class="mb-4">
          <%= label_tag(:category, "Categoría") %>
          <% categories = Product.categories.
            map { |category| [category.humanize, category] } %>
          <%= f.select(:category, options_for_select(categories,
            :selected => f.object.category), {include_blank: true},
            class: "form-select", required: true) %>
        </div>
      </div>

      <div class="col-12 col-md-4">
        <div class="mb-4">
          <%= label_tag(:subcategory, "Subcategoría") %>
          <% categories = Product.subcategories.
            map { |subcategory| [subcategory.humanize, subcategory] } %>
          <%= f.select(:subcategory, options_for_select(categories,
            :selected => f.object.subcategory), {include_blank: true},
            class: "form-select") %>
        </div>
      </div>

      <div class="col-12 col-md-4">
        <div class="mb-4">
          <%= label_tag(:option, "Opción") %>
          <% options = Product.options.
            map { |product| [product.humanize, product] } %>
          <%= f.select(:option, options_for_select(options,
            :selected => f.object.option),
            {include_blank: true}, class: "form-select", required: true) %>
        </div>
      </div>

      <div class="col-12 col-md-4">
        <div class="mb-4">
          <%= label_tag(:size, "Tamaño") %>
          <% sizes = Product.sizes.
            map { |size| [size.humanize.upcase, size] } %>
          <%= f.select(:size, options_for_select(sizes,
            :selected => f.object.size),
            {include_blank: true}, class: "form-select", required: true) %>
        </div>
      </div>

      <div class="col-12 col-md-4">
        <div class="mb-4">
          <%= label_tag(:fit, "Fits like") %>
          <% sizes = Product.fits_like.
            map { |size| [size.humanize.upcase, size] } %>
          <%= f.select(:fit, options_for_select(sizes,
            :selected => f.object.fit),
            {include_blank: true}, class: "form-select") %>
        </div>
      </div>

      <div class="col-12 col-md-4">
        <div class="mb-4">
          <%= label_tag(:quality, "Calidad") %>
          <% qualityArr = Product.quality.
            map { |quality| [quality.capitalize, quality] } %>
          <%= f.select(:quality, options_for_select(qualityArr,
            :selected => f.object.quality),
            {include_blank: true}, class: "form-select") %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-8">
        <div class="mb-4">
          <label >Foto principal</label>
          <div class="form-file">
            <%= f.file_field :main_image,
              class: "form-file-input",
              id: "productImage" %>
            <label class="form-file-label" for="productImage">
              <span class="form-file-text">Seleccionar o cambiar...</span>
              <span class="form-file-button">Buscar</span>
            </label>
          </div>
        </div>
      </div>

      <% if f.object.main_image.attached? %>
        <div class="col-4 text-center">
          <figure class="figure">
            <%= image_tag f.object.main_image,
              class: "figure-img img-fluid rounded",
              style: 'height:4rem;width:auto' %>
            <figcaption class="figure-caption">
              Imagen actual
            </figcaption>
          </figure>
        </div>
      <% end %>
    </div>
    <br>
    <div class="row mt-4">
      <div class="col">
        <%= link_to "Cancelar", admin_products_path, class: "btn btn-outline-danger btn-block"  %>
      </div>
      <div class="col">
        <%= button_tag type: 'submit',
          class: 'btn btn-outline-dark btn-block',
          data: { disable_with: fa_spinner } do %>
          Salvar
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $('#productImage').on('change',function(){
    let fileName = $(this).val().replace("C:\\fakepath\\", "");
    $('.form-file-text').html(fileName);
  })
</script>

app/views/admin/products/_navigation_tabs.html.erb
<ul class="nav nav-tabs nav-fill pt-2 mb-5 mt-3">
	<li class="nav-link <%= 'active' if active == 'products' %>">
		<%= link_to admin_products_path,
			class: "text-decoration-none text-dark font-weight-bold" do %>
			<span>Productos</span>
		<% end %>
	</li>

	<li class="nav-link <%= 'active' if active == 'sold_out' %>">
		<%= link_to admin_soldout_products_path,
			class: "text-decoration-none text-dark font-weight-bold" do %>
			<span>Sold Out</span>
		<% end %>
	</li>
</ul>

app/views/admin/products/edit.html.erb
<div class="row">
	<div class="col-md-9 offset-md-1">
		<div id="new-product">
			<h2 class="text-center my-5">Editar Producto</h2>
			<hr class="mb-3">
			<%= render 'form', product: @product %>
		</div>
	</div>
</div>

app/views/admin/products/index.html.erb
<%= render 'navigation_tabs', active: "products" %>

<div id="products" class="container-fluid">
  <div class="table-responsive">
    <h4 class="mb-2">Producto Activo
      <%= link_to new_admin_product_path,
        class: "float-right btn btn-outline-dark mb-4" do %>
        <i class="fas fa-plus"></i>
        Agregar
      <% end %>
    </h4>
    <table
      data-toggle="table"
      data-search="true"
      class="table table-hover align-middle">
      <thead>
        <tr>
          <th data-sortable="true" scope="col">#</th>
          <th scope="col">Foto</th>
          <th data-sortable="true" scope="col">Nombre</th>
          <th data-sortable="true" scope="col">Marca</th>
          <th data-sortable="true" scope="col">Cantidad</th>
          <th data-sortable="true" scope="col">Categoría</th>
          <th data-sortable="true" scope="col">SubCategoría</th>
          <th data-sortable="true" scope="col">Tipo</th>
          <th data-sortable="true" scope="col">Tamaño</th>
          <th data-sortable="true" scope="col">Fits like</th>
          <th data-sortable="true" scope="col">Calidad</th>
          <th scope="col">Editar</th>
          <th scope="col">Borrar</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index do |product, i| %>
          <tr>
            <th scope="row"><%= i + 1 %></th>
            <td class="text-center">
              <% if product.main_image.attached? %>
                <%= image_tag product.main_image,
                  class: "img-thumbnail", style: 'height:4rem;width:auto' %>
              <% else %>
                <%= image_tag 'otra_vez_blanco.jpg',
                  class: "img-thumbnail", style: 'height:4rem;width:auto' %>
              <% end %>
            </td>
            <td><%= product.title %></td>
            <td><%= product.brand ? product.brand : "-" %></td>
            <td><%= product.quantity %></td>
            <td><%= product.category&.humanize %></td>
            <td><%= product.subcategory&.humanize %></td>
            <td><%= product.option&.humanize %></td>
            <td><%= product.size&.humanize&.upcase %></td>
            <td><%= product.fit&.humanize&.upcase %></td>
            <td><%= product.quality&.capitalize %></td>
            <td>
              <%= link_to edit_admin_product_path(id: product.slug) do %>
                <i class="text-muted fas fa-cog"></i>
              <% end %>
            </td>
            <td class="align-middle">
                <%= link_to admin_product_path(id: product.slug), method: :delete,
                  data: { confirm: 'Seguro? Si borras puede ser cagadal' } do %>
                    <i class="text-danger fas fa-trash-alt"></i>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="row">
	<div class="col-md-9 offset-md-1">
		<div id="new-product">
			<h2 class="text-center my-5">Producto Nuevo</h2>
			<hr class="mb-3">
			<%= render 'form', product: @product %>
		</div>
	</div>
</div>

app/views/admin/products/show.html.erb
<div class="row mt-5">
	<div class="col-md-6 col-12">
		<%= image_tag @product.main_image,
			class: "mx-auto d-block", style: 'height:10vw;width:10vw' if @product.main_image.attached? %>

	</div>
	<div class="col-md-6 col-12">
		<h4><%= @product.title %></h4>
		<p><%= @product.price %></p>
	</div>
</div>

<hr>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>